### ISSUE TITLE
Retrieve the Zotero group data to which the current library_id and api_key has access

### ISSUE THREAD

**Issue by retorquere** [edtechhub/zotero-cli#31] opened 2019-08-12 16:36 UTC

**Comment by retorquere** [comment] 2019-08-12 18:04
Doesn't the `key` command already do this?

**Comment by bjohas** [comment] 2019-08-12 20:18
No, I don't think it does.

**Comment by bjohas** [comment] 2019-08-13 18:49
Duplicate of https://github.com/edtechhub/zotero-cli/issues/30

**Closed as completed by bjohas** 2019-08-13 18:49 UTC
Labels: prio-1
